import type { Innovation, Issue } from "./types";
import { categoryPlaceholder } from "./placeholders";

/** Seed zgłoszeń — Małopolska (Kraków + okolice + inne gminy) */
export const SEED_ISSUES: Issue[] = [
  {
    id: "iss-01",
    title: "Brak oświetlenia przy przystanku",
    description:
      "Przy przystanku przy ul. Lubicz wieczorem jest ciemno. Seniorzy i uczniowie czują się niebezpiecznie.",
    category: "SAFETY",
    latitude: 50.0647,
    longitude: 19.945,
    locationName: "Kraków — Śródmieście",
    upvotes: 34,
    status: "READY_TO_SEND",
    imageUrl: categoryPlaceholder("SAFETY", "Brak oświetlenia przy przystanku"),
    authorName: "Anna K.",
    createdAt: "2026-09-20T10:00:00Z",
    keywords: ["oświetlenie", "przystanek", "bezpieczeństwo", "ciemno"],
  },
  {
    id: "iss-02",
    title: "Wysoki krawężnik przy wejściu do przychodni",
    description:
      "Wejście do przychodni na Nowej Hucie ma wysoki próg — wózek i osoby z laską nie wejdą samodzielnie.",
    category: "ACCESSIBILITY",
    latitude: 50.0722,
    longitude: 20.0374,
    locationName: "Kraków — Nowa Huta",
    upvotes: 28,
    status: "READY_TO_SEND",
    imageUrl: categoryPlaceholder("ACCESSIBILITY", "Wysoki krawężnik przy wejściu do przychodni"),
    authorName: "Marek W.",
    createdAt: "2026-09-18T12:00:00Z",
    keywords: ["krawężnik", "wózek", "przychodnia", "dostępność", "rampa"],
  },
  {
    id: "iss-03",
    title: "Brak kółka programistycznego dla młodzieży",
    description:
      "W Limanowej nie ma bezpłatnych zajęć z programowania. Młodzież dojeżdża do Nowego Sącza.",
    category: "EDUCATION",
    latitude: 49.7061,
    longitude: 20.4228,
    locationName: "Limanowa",
    upvotes: 19,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("EDUCATION", "Brak kółka programistycznego dla młodzieży"),
    authorName: "Ola N.",
    createdAt: "2026-09-25T09:00:00Z",
    keywords: ["programowanie", "młodzież", "zajęcia", "edukacja", "kółko"],
  },
  {
    id: "iss-04",
    title: "Samotność seniorów w bloku",
    description:
      "W bloku przy al. Pokoju wielu seniorów nie wychodzi tygodniami. Brakuje sąsiedzkiego wsparcia.",
    category: "SENIORS",
    latitude: 50.0755,
    longitude: 19.9682,
    locationName: "Kraków — Prądnik Czerwony",
    upvotes: 41,
    status: "SENT",
    imageUrl: categoryPlaceholder("SENIORS", "Samotność seniorów w bloku"),
    authorName: "Piotr S.",
    createdAt: "2026-09-10T08:00:00Z",
    keywords: ["seniorzy", "samotność", "sąsiedzi", "wsparcie", "wizyty"],
  },
  {
    id: "iss-05",
    title: "Dziura w chodniku na trasie do szkoły",
    description:
      "Przy szkole podstawowej w Skawinie chodnik ma głęboką dziurę — dzieci omijają ją jezdnią.",
    category: "INFRASTRUCTURE",
    latitude: 49.9753,
    longitude: 19.8274,
    locationName: "Skawina",
    upvotes: 52,
    status: "READY_TO_SEND",
    imageUrl: categoryPlaceholder("INFRASTRUCTURE", "Dziura w chodniku na trasie do szkoły"),
    authorName: "Ewa L.",
    createdAt: "2026-09-12T14:00:00Z",
    keywords: ["chodnik", "dziura", "szkoła", "droga", "naprawa"],
  },
  {
    id: "iss-06",
    title: "Brak miejsc odpoczynku na deptaku",
    description:
      "Na Rynku w Tarnowie brakuje ławek w cieniu. Seniorzy i rodzice z wózkami nie mają gdzie odpocząć.",
    category: "SENIORS",
    latitude: 50.0121,
    longitude: 20.9858,
    locationName: "Tarnów",
    upvotes: 23,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("SENIORS", "Brak miejsc odpoczynku na deptaku"),
    authorName: "Tomek B.",
    createdAt: "2026-09-22T11:00:00Z",
    keywords: ["ławki", "odpoczynek", "seniorzy", "deptak", "cień"],
  },
  {
    id: "iss-07",
    title: "Słaby zasięg transportu wieczorem",
    description:
      "Ostatni autobus z Zabierzowa do Krakowa odjeżdża zbyt wcześnie — pracownicy wracają taksówką.",
    category: "INFRASTRUCTURE",
    latitude: 50.1167,
    longitude: 19.8,
    locationName: "Zabierzów",
    upvotes: 37,
    status: "READY_TO_SEND",
    imageUrl: categoryPlaceholder("INFRASTRUCTURE", "Słaby zasięg transportu wieczorem"),
    authorName: "Zofia M.",
    createdAt: "2026-09-15T16:00:00Z",
    keywords: ["autobus", "transport", "wieczór", "dojazd", "rozklad"],
  },
  {
    id: "iss-08",
    title: "Brak grupy wsparcia zdrowia psychicznego",
    description:
      "Młodzi mieszkańcy Nowego Sącza czekają miesiącami na psychologa. Brakuje lokalnej grupy rówieśniczej.",
    category: "HEALTH",
    latitude: 49.6219,
    longitude: 20.6972,
    locationName: "Nowy Sącz",
    upvotes: 31,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("HEALTH", "Brak grupy wsparcia zdrowia psychicznego"),
    authorName: "Jan D.",
    createdAt: "2026-09-19T13:00:00Z",
    keywords: ["zdrowie psychiczne", "młodzież", "wsparcie", "grupa", "psycholog"],
  },
  {
    id: "iss-09",
    title: "Nieczytelne oznakowanie dla osób niewidomych",
    description:
      "Przy urzędzie w Olkuszu brak ścieżek naprowadzających i kontrastowych oznaczeń schodów.",
    category: "ACCESSIBILITY",
    latitude: 50.2794,
    longitude: 19.565,
    locationName: "Olkusz",
    upvotes: 18,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("ACCESSIBILITY", "Nieczytelne oznakowanie dla osób niewidomych"),
    authorName: "Kasia R.",
    createdAt: "2026-09-27T10:00:00Z",
    keywords: ["niewidomi", "oznakowanie", "kontrast", "ścieżka", "dostępność"],
  },
  {
    id: "iss-10",
    title: "Pusty lokal mógłby być klubem sąsiedzkim",
    description:
      "Parterowy lokal przy ul. Dietla stoi pusty. Sąsiedzi chcą klubu z kawą i warsztatami.",
    category: "COMMUNITY",
    latitude: 50.056,
    longitude: 19.9445,
    locationName: "Kraków — Kazimierz",
    upvotes: 45,
    status: "READY_TO_SEND",
    imageUrl: categoryPlaceholder("COMMUNITY", "Pusty lokal mógłby być klubem sąsiedzkim"),
    authorName: "Adam P.",
    createdAt: "2026-09-08T09:00:00Z",
    keywords: ["klub sąsiedzki", "lokal", "warsztaty", "społeczność", "kawiarnia"],
  },
  {
    id: "iss-11",
    title: "Brak opieki wytchnieniowej dla opiekunów",
    description:
      "Opiekunowie osób zależnych w Wadowicach nie mają gdzie zostawić bliskich na kilka godzin.",
    category: "SENIORS",
    latitude: 49.8833,
    longitude: 19.4925,
    locationName: "Wadowice",
    upvotes: 26,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("SENIORS", "Brak opieki wytchnieniowej dla opiekunów"),
    authorName: "Magda H.",
    createdAt: "2026-09-21T15:00:00Z",
    keywords: ["opieka wytchnieniowa", "opiekunowie", "seniorzy", "dzień", "wsparcie"],
  },
  {
    id: "iss-12",
    title: "Zalewany parking rowerowy przy dworcu",
    description:
      "Przy dworcu w Chrzanowie stojaki rowerowe są pod wodą po deszczu — rowery rdzewieją.",
    category: "INFRASTRUCTURE",
    latitude: 50.1355,
    longitude: 19.402,
    locationName: "Chrzanów",
    upvotes: 15,
    status: "DRAFT",
    imageUrl: categoryPlaceholder("INFRASTRUCTURE", "Zalewany parking rowerowy przy dworcu"),
    authorName: "Bartek C.",
    createdAt: "2026-09-28T07:00:00Z",
    keywords: ["rower", "parking", "dworzec", "deszcz", "infrastruktura"],
  },
];

/** Biblioteka innowacji społecznych (seed) */
export const SEED_INNOVATIONS: Innovation[] = [
  {
    id: "inn-01",
    title: "Sąsiedzka Latarnia — mikrogranty na oświetlenie",
    sourceMunicipality: "Skawina",
    description:
      "Mieszkańcy zgłaszają ciemne punkty; gmina finansuje lampy solarne z mikrograntu sąsiedzkiego.",
    category: "SAFETY",
    keywords: ["oświetlenie", "lampa", "bezpieczeństwo", "mikrogrant", "przystanek"],
    grantHint: "Mikrogrant sąsiedzki / budżet obywatelski",
  },
  {
    id: "inn-02",
    title: "Rampa w 48h — mobilny warsztat dostępności",
    sourceMunicipality: "Zabierzów",
    description:
      "Wolontariusze + urząd montują tymczasową rampę i zgłaszają trwałą przebudowę do planu inwestycji.",
    category: "ACCESSIBILITY",
    keywords: ["rampa", "krawężnik", "wózek", "dostępność", "przychodnia"],
    grantHint: "Fundusz dostępności / PFRON",
  },
  {
    id: "inn-03",
    title: "Kod od sąsiada — kółka IT w bibliotekach",
    sourceMunicipality: "Nowy Targ",
    description:
      "Biblioteka udostępnia salę; lokalni programiści prowadzą bezpłatne kółka dla młodzieży.",
    category: "EDUCATION",
    keywords: ["programowanie", "kółko", "młodzież", "biblioteka", "edukacja"],
    grantHint: "Grant edukacyjny ROPS / FIO",
  },
  {
    id: "inn-04",
    title: "Telefon do sąsiada — wizyty sąsiedzkie",
    sourceMunicipality: "Wieliczka",
    description:
      "Koordynator łączy wolontariuszy z samotnymi seniorami na cotygodniowe wizyty i zakupy.",
    category: "SENIORS",
    keywords: ["seniorzy", "samotność", "wizyty", "wolontariat", "sąsiedzi"],
    grantHint: "Program senioralny województwa",
  },
  {
    id: "inn-05",
    title: "Łataj z nami — patrol chodnikowy",
    sourceMunicipality: "Niepołomice",
    description:
      "Aplikacja zgłoszeń + szybka ekipa remontowa gminy w ciągu 10 dni roboczych.",
    category: "INFRASTRUCTURE",
    keywords: ["chodnik", "dziura", "naprawa", "droga", "szkoła"],
    grantHint: "Budżet utrzymania dróg gminy",
  },
  {
    id: "inn-06",
    title: "Ławka z cieniem — meble miejskie od mieszkańców",
    sourceMunicipality: "Bochnia",
    description:
      "Projekt partycypacyjny: mieszkańcy wybierają lokalizacje ławek i sadzą drzewa.",
    category: "SENIORS",
    keywords: ["ławki", "cień", "odpoczynek", "deptak", "seniorzy"],
    grantHint: "Budżet obywatelski",
  },
  {
    id: "inn-07",
    title: "Nocny bus pop-up — test linii wieczornych",
    sourceMunicipality: "Krzeszowice",
    description:
      "3-miesięczny pilot dodatkowych kursów wieczornych na podstawie mapy popytu mieszkańców.",
    category: "INFRASTRUCTURE",
    keywords: ["autobus", "transport", "wieczór", "rozklad", "dojazd"],
    grantHint: "Fundusz transportu publicznego",
  },
  {
    id: "inn-08",
    title: "Krąg rozmowy — grupy rówieśnicze zdrowia psychicznego",
    sourceMunicipality: "Myślenice",
    description:
      "Facylitowane spotkania młodzieży w CUS, bez diagnozy, z możliwością skierowania do specjalisty.",
    category: "HEALTH",
    keywords: ["zdrowie psychiczne", "grupa", "młodzież", "wsparcie", "CUS"],
    grantHint: "Program zdrowia psychicznego",
  },
  {
    id: "inn-09",
    title: "Lokal na godzinę — klub sąsiedzki pop-up",
    sourceMunicipality: "Kraków (Krowodrza)",
    description:
      "Gmina udostępnia pusty lokal na popołudnia; mieszkańcy prowadzą kawę i warsztaty.",
    category: "COMMUNITY",
    keywords: ["klub sąsiedzki", "lokal", "warsztaty", "społeczność", "kawiarnia"],
    grantHint: "Program rewitalizacji / CUS",
  },
  {
    id: "inn-10",
    title: "Oddech dla opiekuna — opieka wytchnieniowa 4h",
    sourceMunicipality: "Oświęcim",
    description:
      "Dyżury opiekunów zastępczych w ośrodku dziennym — 4 godziny wytchnienia tygodniowo.",
    category: "SENIORS",
    keywords: ["opieka wytchnieniowa", "opiekunowie", "dzień", "seniorzy", "wsparcie"],
    grantHint: "Usługa społeczna CUS / ROPS",
  },
];
